# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Franklin Sayre
email:
description: >- # this means to ignore newlines until "baseurl:"
  Academic Librarian at Thompson Rivers University 
twitter_username: username
github_username: fdsayre
minimal_mistakes_skin: dark
search: true
repository: "fdsayre/fdsayre.github.io"
locale: "en-US"
url: https://fdsayre.github.io/
excerpt_separator: "<!--more-->"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-1H15HLBEVC"
    anonymize_ip: false # default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  #- jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Franklin Sayre"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I’m the Makerspace Librarian at Thompson Rivers University and also Co-Chair the Librarians’ Department. These days I am particularly interested in creating active learning spaces that foster belonging and encouraging sustainability and critical thinking about technology and information."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:fsayre@tru.ca"
    - label: "Bluesky"
      icon: "fas fa-fw fa-link"
      url: "https://bsky.app/profile/franklinsayre.bsky.social"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/franklin-sayre/"
    - label: "TRU Library Makerspace"
      icon: "fas fa-fw fa-link"
      url: "https://makerspace.trubox.ca/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/fdsayre"
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:fsayre@tru.ca"
    - label: "Bluesky"
      icon: "fas fa-fw fa-link"
      url: "https://bsky.app/profile/franklinsayre.bsky.social"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/franklin-sayre/"
    - label: "TRU Library Makerspace"
      icon: "fas fa-fw fa-link"
      url: "https://makerspace.trubox.ca/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/fdsayre"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _apar2024
  - scope:
      path: ""
      type: apar2024
    values:
      toc: true
      layout: single
      author_profile: true
      share: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      toc: true
      layout: single
      author_profile: true
      share: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


collections:
  apar2024:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/